import type { Metadata, Viewport } from "next";
import { Baloo_2, Nunito } from "next/font/google";
import { KitProvider } from "@/components/kit-provider";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

export const viewport: Viewport = {
  themeColor: "#1e5ae8",
};

const baloo = Baloo_2({
  variable: "--font-baloo",
  subsets: ["latin"],
  weight: ["500", "600", "700", "800"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WordWave — learn a language, five minutes at a time",
  description: "Lessons, streaks, and spaced repetition — on your phone or PC.",
  applicationName: "WordWave",
  appleWebApp: { capable: true, statusBarStyle: "default", title: "WordWave" },
  icons: {
    icon: [{ url: "/icon-192.png", sizes: "192x192", type: "image/png" }],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${baloo.variable} ${nunito.variable} h-full antialiased`}>
      <head>
        {/* Hand-written rather than generated by a manifest.ts: the manifest sits behind
            the login gate, so the browser must send the session cookie when fetching it,
            and Next only adds `crossorigin="use-credentials"` on Vercel preview builds
            (work order criterion 23; the Word Forge finding). */}
        <link rel="manifest" href="/manifest.webmanifest" crossOrigin="use-credentials" />
      </head>
      <body className="min-h-full flex flex-col font-sans">
        <KitProvider>{children}</KitProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
