/* Spanish golden-file lock.
 *
 * The Spanish course is finished and in use. Every change from here on is aimed
 * at Latin, and the danger is that a "shared engine" tweak silently alters
 * Spanish output — exactly how j→i / v→u folding, added for Latin, quietly
 * loosened Spanish typed-answer grading.
 *
 * This hashes the compiled Spanish course (every word id, section, unit, lesson
 * and challenge, including the generated challenge JSON) and compares it to the
 * committed lock file. Any drift fails, loudly, with the offending section named.
 *
 *   npx tsx scripts/spanish-lock.ts            # check (exits 1 on drift)
 *   npx tsx scripts/spanish-lock.ts --update   # accept current output as the new baseline
 *
 * Updating is a deliberate act: only do it when the Spanish change was intended.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { courses } from "../prisma/course-data";
import { buildCourse } from "../prisma/course-build";

const LOCK_PATH = path.join(__dirname, "..", "prisma", "spanish-lock.json");

const sha = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");

interface Lock {
  note: string;
  course: string;
  counts: { words: number; sections: number; units: number; lessons: number; challenges: number };
  overall: string;
  sections: Record<string, string>;
}

function buildLock(): Lock {
  const course = courses.find((c) => c.code === "es");
  if (!course) throw new Error("No Spanish course found in course-data");

  const built = buildCourse(course);

  let units = 0;
  let lessons = 0;
  let challenges = 0;
  const sections: Record<string, string> = {};
  for (const section of built.sections) {
    units += section.units.length;
    for (const unit of section.units) {
      lessons += unit.lessons.length;
      for (const lesson of unit.lessons) challenges += lesson.challenges.length;
    }
    sections[section.id] = sha(section);
  }

  return {
    note: "Generated by scripts/spanish-lock.ts. Do not hand-edit. Regenerate ONLY when a Spanish change is intentional.",
    course: "es",
    counts: { words: built.words.length, sections: built.sections.length, units, lessons, challenges },
    overall: sha(built),
    sections,
  };
}

const current = buildLock();
const updating = process.argv.includes("--update");
const existed = existsSync(LOCK_PATH);

if (updating || !existed) {
  writeFileSync(LOCK_PATH, `${JSON.stringify(current, null, 2)}\n`, "utf8");
  console.log(`${existed ? "Updated" : "Created"} ${path.relative(process.cwd(), LOCK_PATH)}`);
  console.log(`  overall ${current.overall}`);
  console.log(`  ${JSON.stringify(current.counts)}`);
  process.exit(0);
}

const saved: Lock = JSON.parse(readFileSync(LOCK_PATH, "utf8"));

if (saved.overall === current.overall) {
  console.log(`Spanish lock OK — ${current.overall.slice(0, 16)}… ${JSON.stringify(current.counts)}`);
  process.exit(0);
}

console.error("SPANISH LOCK FAILED — the compiled Spanish course changed.\n");

const countKeys = Object.keys(current.counts) as (keyof Lock["counts"])[];
for (const key of countKeys)
  if (saved.counts[key] !== current.counts[key])
    console.error(`  count ${key}: ${saved.counts[key]} -> ${current.counts[key]}`);

const ids = new Set([...Object.keys(saved.sections), ...Object.keys(current.sections)]);
for (const id of ids) {
  if (!(id in current.sections)) console.error(`  section removed: ${id}`);
  else if (!(id in saved.sections)) console.error(`  section added:   ${id}`);
  else if (saved.sections[id] !== current.sections[id]) console.error(`  section changed: ${id}`);
}

console.error(
  "\nIf this change was intentional, re-run with --update and commit the new lock." +
    "\nIf not, you have altered Spanish while working on another course — revert it."
);
process.exit(1);
